---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Pavell.
--- DateTime: 22.03.2025 12:00
---

require 'build' {
    game = [[N:\Warcraft III\_retail_\x86_64]],
    run = "game",
    src = {
        'src\\lib',
        'src\\inc',
        'src\\data.lua',
        'src\\main.lua'
    }
}