---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Pavell.
--- DateTime: 24.03.2025 19:44
---

SimpleTypeFrame = {}
---new
---@param name string
---@param type string
---@param parent framehandle
---@param inherits string
---@param context integer
function SimpleTypeFrame:new(name, type, parent, inherits, context)
    local frame = BlzCreateFrameByType(type, name, parent, inherits or "", context or 0)
    local obj = {
        handle = frame
    }

    ---setSize
    ---@param width number
    ---@param height number
    function obj:setSize(width, height)
        BlzFrameSetSize(self.handle, width, height)
        return self
    end

    ---setAbsPoint
    ---@param point framepointtype
    ---@param x number
    ---@param y number
    function obj:setAbsPoint(point, x, y)
        BlzFrameSetAbsPoint(self.handle, point, x, y)
        return self
    end

    ---setRelativePoint
    ---@param selfPoint framepointtype
    ---@param relativeFrame framehandle
    ---@param relativePoint framepointtype
    ---@param x number
    ---@param y number
    function obj:setRelativePoint(selfPoint, relativeFrame, relativePoint, x, y)
        BlzFrameSetPoint(self.handle, selfPoint, relativeFrame, relativePoint, x, y)
        return self
    end

    setmetatable(obj, self)
    self.__index = self
    return obj
end

SimpleEmptyFrame = {}
setmetatable(SimpleEmptyFrame, {__index = SimpleTypeFrame})
---new
---@param name string
---@param parent framehandle
---@param context integer
function SimpleEmptyFrame:new(name, parent, context)
    return SimpleTypeFrame:new(name, "FRAME", parent, "", context)
end

SimpleBackdropTextureFrame = {}
setmetatable(SimpleBackdropTextureFrame, { __index = SimpleTypeFrame})
---new
---@param name string
---@param parent framehandle
---@param context integer
function SimpleBackdropTextureFrame:new(name, texturePath, parent, context)
    local frame = SimpleTypeFrame:new(name, "BACKDROP", parent, "", context)

    function frame:setTexture(texturePath)
        BlzFrameSetTexture(self.handle, texturePath, 0, true)
    end

    frame:setTexture(texturePath)
    return frame;
end

TextureFrame = {}
---new
---@param namePrefix string
---@param texturePath string
---@param parent framehandle
---@param context integer
function TextureFrame:new(namePrefix, texturePath, parent, context)
    local coverFrame = SimpleEmptyFrame:new(namePrefix .. "_cover", parent, context)
    local textureFrame = SimpleBackdropTextureFrame:new(namePrefix .. "_icon", texturePath, coverFrame.handle, context)
    BlzFrameSetAllPoints(textureFrame.handle, coverFrame.handle)

    local obj = {
        cover = coverFrame,
        texture = textureFrame
    }

    function obj:setTexture(texturePath)
        self.texture:setTexture(texturePath)
        return self
    end

    setmetatable(obj, self)
    self.__index = self
    return obj
end