---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by WGPavell.
--- DateTime: 22.03.2025 16:07
---

RaceUnits = {
    race = "",
    codes = {}
}
RaceUnits.__index = RaceUnits

function RaceUnits:new(race, codes)
    local data = {
        race = race,
        codes = codes
    }
    setmetatable(data, self)
    self.__index = self
    return data
end

local TargetData = {
    ground = false,
    air = false
}
TargetData.__index = TargetData

function TargetData:new(ground, air)
    local data = {
        ground = ground,
        air = air
    }
    setmetatable(data, self)
    self.__index = self
    return data
end

UnitData = {
    code = "",
    name = "",
    is_hero = false,
    food_cost = 0,
    unit_target = TargetData:new(false, false),
    attack_target = TargetData:new(false, false)
}
UnitData.__index = UnitData

function UnitData:new(code, name, is_hero, food_cost, unit_target, attack_target)
    local data = {
        code = code,
        name = name,
        is_hero = is_hero,
        food_cost = food_cost,
        unit_target = unit_target,
        attack_target = attack_target
    }
    setmetatable(data, self)
    self.__index = self
    return data
end