---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by WGPavell.
--- DateTime: 27.03.2025 19:02
---

---DelayCallback
---@param timeout number
---@param callback function
function DelayCallback(timeout, callback)
    TimerStart(CreateTimer(), timeout, false, callback)
end

---PlayInterfaceSound
---@param fileName string
---@param volume integer
function PlayInterfaceSound(fileName, volume)
    local sound = CreateSound(fileName, false, false, false, 0, 0, "DefaultEAXON")
    SetSoundVolume(sound, volume or 127)
    StartSound(sound)
    KillSoundWhenDone(sound)
end