---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by WGPavell.
--- DateTime: 22.03.2025 13:10
---

TARGET_FLAG_NONE_INT = 1
TARGET_FLAG_GROUND_INT = 2
TARGET_FLAG_AIR_INT = 4
TARGET_FLAG_STRUCTURE_INT = 8
TARGET_FLAG_WARD_INT = 16
TARGET_FLAG_ITEM_INT = 32
TARGET_FLAG_TREE_INT = 64
TARGET_FLAG_WALL_INT = 128
TARGET_FLAG_DEBRIS_INT = 256
TARGET_FLAG_DECORATION_INT = 512
TARGET_FLAG_BRIDGE_INT = 1024

function dump(o)
    if type(o) == 'table' then
        local s = '{ '
        for k,v in pairs(o) do
            if type(k) ~= 'number' then k = '"'..k..'"' end
            s = s .. '['..k..'] = ' .. dump(v) .. ','
        end
        return s .. '} '
    else
        return tostring(o)
    end
end

---debugPrint
---@param message string
function debugPrint(message)
    DisplayTextToPlayer(Player(0), 0, 0, message)
end

---debugPrintAny
---@param object any
function debugPrintAny(object)
    debugPrint(tostring(object))
end

-- Why I don't use GetLocalizedString here? Because of some reason it doesn't work before main function
unitGroups = {
    {
        id = "human",
        race_key = "KEY_HUMAN",
        unit_codes = {'hpea', 'hfoo', 'hrif', 'hkni', 'hsor', 'hmpr', 'hspt', 'hgyr', 'hmtm', 'hmtt', 'hgry', 'hdhw', 'Hpal', 'Hamg', 'Hmkg', 'Hblm'}
    },
    {
        id = "orc",
        race_key = "KEY_ORC",
        unit_codes = {'opeo', 'ogru', 'ohun', 'ocat', 'oshm', 'odoc', 'ospw', 'orai', 'okod', 'owyv', 'otbr', 'otau', 'Obla', 'Ofar', 'Otch', 'Oshd'}
    },
    {
        id = "undead",
        race_key = "KEY_UNDEAD",
        unit_codes = {'uaco', 'ugho', 'ucry', 'ugar', 'unec', 'uban', 'umtw', 'uabo', 'uobs', 'ufro', 'Udea', 'Ulic', 'Udre', 'Ucrl'}
    },
    {
        id = "nightelf",
        race_key = "KEY_NIGHTELF",
        unit_codes = {'earc', 'esen', 'ebal', 'edry', 'edoc', 'emtg', 'ehip', 'ehpr', 'edot', 'efdr', 'echm', 'Ekee', 'Emoo', 'Edem', 'Ewar'}
    },
}

upgrades = {
    {
        code = 'Rhla',
        units = {'hdhw', 'hgry', 'hmtm', 'hrif'}
    },
    {
        code = 'Rhme',
        units = {'hdhw', 'hfoo', 'hgry', 'hkni', 'hspt'}
    },
    {
        code = 'Rguv',
        units = {'hdhw', 'hfoo', 'hgry', 'hgyr', 'hkni', 'hmpr', 'hmtm', 'hmtt', 'hpea', 'hrif', 'hsor', 'hspt', 'ocat', 'odoc', 'ogru', 'ohun', 'okod', 'opeo', 'orai', 'oshm', 'ospw', 'otau', 'otbr', 'owyv', 'uabo', 'uaco', 'uban', 'ucry', 'ufro', 'ugar', 'ugho', 'umtw', 'unec', 'uobs'}
    },
    {
        code = 'Rhan',
        units = {'hdhw', 'hgry', 'hkni'}
    },
    {
        code = 'Rhcd',
        units = {'hdhw'}
    },
    {
        code = 'Rhar',
        units = {'hfoo', 'hgyr', 'hkni', 'hmtt', 'hspt'}
    },
    {
        code = 'Rhde',
        units = {'hfoo'}
    },
    {
        code = 'Rhpm',
        units = {'hfoo', 'hkni', 'hmpr', 'hrif', 'hsor', 'hspt'}
    },
    {
        code = 'Rhhb',
        units = {'hgry'}
    },
    {
        code = 'Rhra',
        units = {'hgyr', 'hmtm', 'hmtt', 'hrif'}
    },
    {
        code = 'Rhgb',
        units = {'hgyr'}
    },
    {
        code = 'Rhfc',
        units = {'hgyr'}
    },
    {
        code = 'Rhsb',
        units = {'hkni'}
    },
    {
        code = 'Rhpt',
        units = {'hmpr'}
    },
    {
        code = 'Rhfl',
        units = {'hmtm'}
    },
    {
        code = 'Rhfs',
        units = {'hmtm'}
    },
    {
        code = 'Rhrt',
        units = {'hmtt'}
    },
    {
        code = 'Rhlh',
        units = {'hpea'}
    },
    {
        code = 'Rhri',
        units = {'hrif'}
    },
    {
        code = 'Rhst',
        units = {'hsor'}
    },
    {
        code = 'Rhss',
        units = {'hspt'}
    },
    {
        code = 'Roar',
        units = {'ocat', 'ogru', 'ohun', 'orai', 'otau', 'otbr', 'owyv'}
    },
    {
        code = 'Rora',
        units = {'ocat', 'ohun', 'otbr', 'owyv'}
    },
    {
        code = 'Robf',
        units = {'ocat'}
    },
    {
        code = 'Rolf',
        units = {'ocat'}
    },
    {
        code = 'Rowd',
        units = {'odoc'}
    },
    {
        code = 'Rotr',
        units = {'odoc', 'ohun', 'otbr'}
    },
    {
        code = 'Ropm',
        units = {'odoc', 'ogru', 'ohun', 'orai', 'oshm', 'ospw', 'otau'}
    },
    {
        code = 'Rome',
        units = {'ogru', 'orai', 'otau'}
    },
    {
        code = 'Robs',
        units = {'ogru'}
    },
    {
        code = 'Ropg',
        units = {'ogru', 'opeo', 'orai'}
    },
    {
        code = 'Robk',
        units = {'ohun'}
    },
    {
        code = 'Rwdm',
        units = {'okod'}
    },
    {
        code = 'Roen',
        units = {'orai'}
    },
    {
        code = 'Rost',
        units = {'oshm'}
    },
    {
        code = 'Rowt',
        units = {'ospw'}
    },
    {
        code = 'Rows',
        units = {'otau'}
    },
    {
        code = 'Rovs',
        units = {'owyv'}
    },
    {
        code = 'Reuv',
        units = {'Edem', 'Ekee', 'Emoo', 'Ewar', 'earc', 'ebal', 'echm', 'edoc', 'edot', 'edry', 'efdr', 'ehip', 'ehpr', 'emtg', 'esen'}
    },
    {
        code = 'Resm',
        units = {'earc', 'ebal', 'ehpr', 'esen'}
    },
    {
        code = 'Rema',
        units = {'earc', 'ehpr', 'esen'}
    },
    {
        code = 'Reib',
        units = {'earc', 'ehpr'}
    },
    {
        code = 'Remk',
        units = {'earc', 'ehpr'}
    },
    {
        code = 'Repm',
        units = {'earc', 'edoc', 'edot', 'edry', 'emtg', 'esen'}
    },
    {
        code = 'Repb',
        units = {'ebal'}
    },
    {
        code = 'Resw',
        units = {'echm', 'edry', 'efdr', 'ehip', 'emtg'}
    },
    {
        code = 'Rerh',
        units = {'echm', 'edry', 'efdr', 'ehip', 'emtg'}
    },
    {
        code = 'Recb',
        units = {'echm'}
    },
    {
        code = 'Redc',
        units = {'edoc'}
    },
    {
        code = 'Reeb',
        units = {'edoc'}
    },
    {
        code = 'Redt',
        units = {'edot'}
    },
    {
        code = 'Reec',
        units = {'edot'}
    },
    {
        code = 'Resi',
        units = {'edry'}
    },
    {
        code = 'Reht',
        units = {'ehip', 'ehpr'}
    },
    {
        code = 'Rers',
        units = {'emtg'}
    },
    {
        code = 'Rehs',
        units = {'emtg'}
    },
    {
        code = 'Resc',
        units = {'esen'}
    },
    {
        code = 'Remg',
        units = {'esen'}
    },
    {
        code = 'Ruar',
        units = {'uabo', 'ugho'}
    },
    {
        code = 'Rume',
        units = {'uabo', 'ugho', 'umtw'}
    },
    {
        code = 'Rupc',
        units = {'uabo', 'umtw'}
    },
    {
        code = 'Rupm',
        units = {'uabo', 'uban', 'ucry', 'ugho', 'unec'}
    },
    {
        code = 'Ruac',
        units = {'uabo', 'ugho'}
    },
    {
        code = 'Ruba',
        units = {'uban'}
    },
    {
        code = 'Rura',
        units = {'ucry', 'ufro', 'ugar'}
    },
    {
        code = 'Rucr',
        units = {'ucry', 'ufro', 'ugar'}
    },
    {
        code = 'Ruwb',
        units = {'ucry'}
    },
    {
        code = 'Rubu',
        units = {'ucry'}
    },
    {
        code = 'Rufb',
        units = {'ufro'}
    },
    {
        code = 'Rusf',
        units = {'ugar'}
    },
    {
        code = 'Rugf',
        units = {'ugho'}
    },
    {
        code = 'Rune',
        units = {'unec'}
    },
    {
        code = 'Rusm',
        units = {'unec'}
    },
    {
        code = 'Rusp',
        units = {'uobs'}
    }
}

heroAbilities = {
    Hamg = {'AHbz', 'AHab', 'AHwe', 'AHmt'},
    Hblm = {'AHfs', 'AHbn', 'AHdr', 'AHpx'},
    Hmkg = {'AHtc', 'AHtb', 'AHbh', 'AHav'},
    Hpal = {'AHhb', 'AHds', 'AHre', 'AHad'},
    Obla = {'AOwk', 'AOcr', 'AOmi', 'AOww'},
    Ofar = {'AOfs', 'AOsf', 'AOcl', 'AOeq'},
    Oshd = {'AOhw', 'AOhx', 'AOsw', 'AOvd'},
    Otch = {'AOsh', 'AOae', 'AOre', 'AOws'},
    Edem = {'AEmb', 'AEim', 'AEev', 'AEme'},
    Ekee = {'AEer', 'AEfn', 'AEah', 'AEtq'},
    Emoo = {'AHfa', 'AEst', 'AEar', 'AEsf'},
    Ewar = {'AEbl', 'AEfk', 'AEsh', 'AEsv'},
    Ucrl = {'AUim', 'AUts', 'AUcb', 'AUls'},
    Udea = {'AUdc', 'AUdp', 'AUau', 'AUan'},
    Udre = {'AUav', 'AUsl', 'AUcs', 'AUin'},
    Ulic = {'AUfn', 'AUfu', 'AUdr', 'AUdd'}
}
abilitiesIcons = {}

SPELL_IMMUNE_ABILITIES = {'Amim', 'ACm2', 'ACm3', 'ACmi'}
ANTI_AIR_ABILITIES = {'Aens', 'Aweb', 'ACen', 'ACwb'}

unitsUpgradesDependencies = {}
unitList = {}

OnInit.map(function()
    for _, upgrade in ipairs(upgrades) do
        upgrade.name = GetAbilityName(FourCC(upgrade.code))
        upgrade.icon = BlzGetAbilityIcon(FourCC(upgrade.code))
        for _, unit in ipairs(upgrade.units) do
            if unitsUpgradesDependencies[unit] == nil then
                unitsUpgradesDependencies[unit] = {}
            end
            table.insert(unitsUpgradesDependencies[unit], upgrade)
        end
    end

    for _, abilityList in pairs(heroAbilities) do
        for _, ability in ipairs(abilityList) do
            if abilitiesIcons[ability] == nil then
                abilitiesIcons[ability] = BlzGetAbilityIcon(FourCC(ability))
            end
        end
    end

    local subjectPlayer = Player(PLAYER_NEUTRAL_PASSIVE)
    for _, group in ipairs(unitGroups) do
        local unitsData = {}
        for _, code in ipairs(group.unit_codes) do
            local subject = CreateUnit(subjectPlayer, FourCC(code), 0, 0, 0)
            ShowUnit(subject, false)
            if unitsUpgradesDependencies[code] ~= nil then
                for _, upgrade in ipairs(unitsUpgradesDependencies[code]) do
                    SetPlayerTechResearched(subjectPlayer, FourCC(upgrade.code), GetPlayerTechMaxAllowed(subjectPlayer, FourCC(upgrade.code)))
                end
            end
            DelayCallback(0.01, function()
                local targeted_as = BlzGetUnitIntegerField(subject, UNIT_IF_TARGETED_AS)
                local attack1_enabled = BlzGetUnitWeaponBooleanField(subject, UNIT_WEAPON_BF_ATTACKS_ENABLED, 0)
                local attack1_targets = BlzGetUnitWeaponIntegerField(subject, UNIT_WEAPON_IF_ATTACK_TARGETS_ALLOWED, 0)
                local attack1_magic = ConvertAttackType(BlzGetUnitWeaponIntegerField(subject, UNIT_WEAPON_IF_ATTACK_ATTACK_TYPE, 0)) == ATTACK_TYPE_MAGIC
                local attack2_enabled = BlzGetUnitWeaponBooleanField(subject, UNIT_WEAPON_BF_ATTACKS_ENABLED, 1)
                local attack2_targets = BlzGetUnitWeaponIntegerField(subject, UNIT_WEAPON_IF_ATTACK_TARGETS_ALLOWED, 1)
                local attack2_magic = ConvertAttackType(BlzGetUnitWeaponIntegerField(subject, UNIT_WEAPON_IF_ATTACK_ATTACK_TYPE, 1)) == ATTACK_TYPE_MAGIC
                local have_immune = false
                for _, spellId in ipairs(SPELL_IMMUNE_ABILITIES) do
                    if GetUnitAbilityLevel(subject, FourCC(spellId)) > 0 then
                        have_immune = true
                        break
                    end
                end
                local have_anti_air = false
                for _, spellId in ipairs(ANTI_AIR_ABILITIES) do
                    if GetUnitAbilityLevel(subject, FourCC(spellId)) > 0 then
                        have_anti_air = true
                        break
                    end
                end
                table.insert(unitsData, {
                    code = code,
                    name = BlzGetUnitStringField(subject, UNIT_SF_NAME),
                    is_hero = IsUnitType(subject, UNIT_TYPE_HERO),
                    food_cost = GetUnitFoodUsed(subject),
                    unit_target = {
                        ground = targeted_as & TARGET_FLAG_GROUND_INT ~= 0,
                        air = targeted_as & TARGET_FLAG_AIR_INT ~= 0,
                        immune = have_immune
                    },
                    attack_target = {
                        ground = (attack1_enabled and attack1_targets & TARGET_FLAG_GROUND_INT ~= 0) or (attack2_enabled and attack2_targets & TARGET_FLAG_GROUND_INT ~= 0),
                        air = (attack1_enabled and attack1_targets & TARGET_FLAG_AIR_INT ~= 0) or (attack2_enabled and attack2_targets & TARGET_FLAG_AIR_INT ~= 0) or have_anti_air,
                        magic = (attack1_enabled or attack2_enabled) and ((not attack1_enabled or (attack1_enabled and attack1_magic)) and (not attack2_enabled or (attack2_enabled and attack2_magic))),
                    },
                    icon = BlzGetAbilityIcon(FourCC(code)),
                    battles = 0,
                    victories = 0,
                    total_died = 0,
                    total_killed = 0,
                    history = {}
                })
                RemoveUnit(subject)
            end)
        end
        table.insert(unitList, {
            id = group.id,
            race = GetLocalizedString(group.race_key),
            units = unitsData
        })
    end
    --TimerStart(CreateTimer(), 0.1, false, function()
    --    debugPrint(dump(unitList))
    --end)
end)