---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Pavell.
--- DateTime: 24.03.2025 18:58
---

FRAMES_TO_HIDE = {'ConsoleBottomBarOverlay', 'CommandBarFrame'}
for i = 0, 11 do
    table.insert(FRAMES_TO_HIDE, "CommandButton_" .. i)
end

FULLSCREEN_CANVAS_SIZE_REFRESH_PERIOD = 0.02
--- @type SimpleEmptyFrame
fullscreenWrapperFrame = nil
--- @type SimpleEmptyFrame
fullscreenCanvasFrame = nil
fullscreenCanvasTimer = CreateTimer()

function GetScreenFrameWidth()
    return BlzGetLocalClientWidth() / BlzGetLocalClientHeight() * 0.6
end

function UpdateFullscreenCanvasSize()
    BlzFrameSetSize(fullscreenCanvasFrame.handle, GetScreenFrameWidth(), 0.6)
end

--- @type TextureFrame
leftSideFrame = nil
--- @type TextureFrame
rightSideFrame = nil

OnInit.map(function()
    -- Hide all unnecessary frames
    BlzHideOriginFrames(true)
    local framesToHide = {}
    for _, frameName in ipairs(FRAMES_TO_HIDE) do
        table.insert(framesToHide, BlzGetFrameByName(frameName, 0))
    end
    for _, frame in ipairs(framesToHide) do
        BlzFrameSetVisible(frame, false)
    end

    -- Creating fullscreen frame
    local mainFrame = BlzGetFrameByName("ConsoleUIBackdrop", 0)
    fullscreenWrapperFrame = SimpleEmptyFrame:new("FullscreenWrapper", mainFrame)
    fullscreenCanvasFrame = SimpleEmptyFrame:new("FullscreenCanvas", fullscreenWrapperFrame.handle)
    BlzFrameSetVisible(fullscreenCanvasFrame.handle, false)
    UpdateFullscreenCanvasSize()
    TimerStart(fullscreenCanvasTimer, FULLSCREEN_CANVAS_SIZE_REFRESH_PERIOD, true, UpdateFullscreenCanvasSize)
    BlzFrameSetAbsPoint(fullscreenCanvasFrame.handle, FRAMEPOINT_BOTTOM, 0.4, 0)
    leftSideFrame = TextureFrame:new("left_side_icon", "", fullscreenWrapperFrame.handle)
    leftSideFrame.cover:setSize(0.045, 0.045):setRelativePoint(FRAMEPOINT_TOPLEFT, fullscreenCanvasFrame.handle, FRAMEPOINT_TOPLEFT, 0.03, -0.03)
    rightSideFrame = TextureFrame:new("right_side_icon", "", fullscreenWrapperFrame.handle)
    rightSideFrame.cover:setSize(0.045, 0.045):setRelativePoint(FRAMEPOINT_TOPRIGHT, fullscreenCanvasFrame.handle, FRAMEPOINT_TOPRIGHT, -0.03, -0.03)
    --local textureFrame = BlzCreateFrameByType("BACKDROP", "texture_frame", fullscreenWrapperFrame.handle, "", 0)
    --BlzFrameSetTexture(textureFrame, "ReplaceableTextures\\CommandButtons\\BTNPriest", 0, true)
    --BlzFrameSetSize(textureFrame, 0.5, 0.05)
    --BlzFrameSetPoint(textureFrame, FRAMEPOINT_TOPLEFT, fullscreenCanvasFrame.handle, FRAMEPOINT_TOPLEFT, 0, 0)
    --local textureFrame2 = BlzCreateFrameByType("BACKDROP", "texture_frame", fullscreenWrapperFrame.handle, "", 0)
    --BlzFrameSetTexture(textureFrame2, "ReplaceableTextures\\CommandButtons\\BTNPriest", 0, true)
    --BlzFrameSetSize(textureFrame2, 0.05, 0.05)
    --BlzFrameSetPoint(textureFrame2, FRAMEPOINT_TOPRIGHT, fullscreenCanvasFrame.handle, FRAMEPOINT_TOPRIGHT, 0, 0)
    --BlzFrameSetPoint(textureFrame2, FRAMEPOINT_LEFT, textureFrame, FRAMEPOINT_RIGHT, 0, 0)
    --BlzFrameSetPoint(textureFrame, FRAMEPOINT_RIGHT, textureFrame2, FRAMEPOINT_LEFT, 0, 0)
    --local simpleFrame = BlzCreateSimpleFrame("UpperButtonBarButtonTemplate", BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), 0)
    --BlzFrameSetPoint(simpleFrame, FRAMEPOINT_TOPLEFT, BlzGetOriginFrame(ORIGIN_FRAME_HERO_BAR, 0), FRAMEPOINT_TOPLEFT, 0.1, -0.1)
    --local icon = BlzCreateFrameByType("SIMPLESTATUSBAR", "", BlzGetFrameByName("ConsoleUI", 0), "", 0)
    --BlzFrameClearAllPoints(icon)
    --BlzFrameSetPoint(icon, FRAMEPOINT_BOTTOM, simpleFrame, FRAMEPOINT_TOP, 0, 0.006)
    --BlzFrameSetSize(icon, 0.04, 0.04)
    --BlzFrameSetTexture(icon, "ReplaceableTextures\\CommandButtons\\BTNPriest", 0, false)
    --BlzFrameSetTooltip(simpleFrame, icon)
    ---- SimpleFrameTooltip is not hidden by calling BlzFrameSetTooltip, hide it
    --BlzFrameSetVisible(icon, false)
    --BlzEnableUIAutoPosition(false)
    --local frame = BlzCreateSimpleFrame("simple_test", BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), 0)
    --local blademaster = BlzCreateFrameByType("BACKDROP", "Blademaster", frame, "", 0)
    --BlzFrameSetAllPoints(blademaster, frame)
    ----BlzFrameSetAlpha(BlzGetFrameByName("ConsoleUIBackdrop",0), 0)
    ----BlzFrameSetAbsPoint(blademaster, FRAMEPOINT_TOPLEFT, -0.02, 0.1)
    ----BlzFrameSetVisible(BlzGetOriginFrame(ORIGIN_FRAME_HERO_BAR, 0), true)
    --BlzFrameSetPoint(frame, FRAMEPOINT_TOPLEFT, BlzGetOriginFrame(ORIGIN_FRAME_HERO_BAR, 0), FRAMEPOINT_TOPLEFT, 0.1, 0)
    --BlzFrameSetSize(blademaster, 0.05, 0.05)
    --BlzFrameSetTexture(blademaster, "ReplaceableTextures\\CommandButtons\\BTNHeroBlademaster.blp",0, true)
end)