---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by WGPavell.
--- DateTime: 22.03.2025 12:29
---

OnInit.map(function()
    FogEnable(false)
    FogMaskEnable(false)
    local unit = CreateUnit(Player(0), FourCC('ugar'), 0, 0, 0)
    debugPrintAny(dump(unitsUpgradesDependencies))
end)

OnInit.final(function()
    for _, raceData in ipairs(unitList) do
        debugPrint(raceData.units[1].icon)
    end
end)